import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import Script from 'next/script'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://www.dyzbuilding.cl'

export const metadata: Metadata = {
  title: 'Retail HVAC & Refrigeration in Chile — Supermarkets & Shopping Centers',

  description:
    'HVAC and commercial refrigeration for retail in Chile: supermarket VRF, display case systems, CO₂ transcritical refrigeration, multi-store SLA maintenance. D&Z handles both HVAC and refrigeration under one contract.',
  alternates: {
    canonical: `${siteUrl}/en/sectors/retail/`,
    languages: {
      en: `${siteUrl}/en/sectors/retail/`,
      es: `${siteUrl}/sectores/retail/`,
    },
  },
  openGraph: {
    title: 'Retail HVAC Chile — Supermarkets, Malls & Chain Stores | D&Z Building',
    description:
      'Integrated HVAC + commercial refrigeration for supermarkets and retail in Chile. VRF sales floor, CO₂ transcritical racks, multi-store SLA contracts.',
    url: `${siteUrl}/en/sectors/retail/`,
    locale: 'en_US',
    type: 'website',
  },
  robots: { index: true, follow: true },
}

const SOLUTIONS = [
  {
    titulo: 'Sales Floor HVAC',
    subtitulo: 'VRF / Fan-Coil · Thermal simulation',
    desc: 'VRF multi-split or centralized fan-coil systems for supermarket and hypermarket sales floors. The key in retail is balancing customer comfort with the heat generated by open display cases and lighting. We use thermal simulation tools to optimize diffuser layout and system sizing — preventing the overcooling that wastes energy without improving comfort.',
  },
  {
    titulo: 'Refrigerated Display Cases',
    subtitulo: 'T −2 to +8°C · A+ efficiency',
    desc: 'Installation and maintenance of refrigerated gondolas, frozen food islands, and butcher/deli display cases. We work with centralized compressor rack systems using HFC refrigerants or CO₂ transcritical (R-744), which reduce energy consumption up to 30% vs. decentralized systems using R-404A.',
  },
  {
    titulo: 'Machine Room & Compressor Racks',
    subtitulo: 'Centralized refrigeration · Remote monitoring',
    desc: 'Design and installation of machine rooms with semi-hermetic or hermetic compressor racks, rooftop remote condensers, control panels with remote monitoring, and heat recovery systems for hot water or back-of-house heating. We handle the SEC permit process for refrigerant installation drawings.',
  },
  {
    titulo: 'Back-of-House Ventilation & Cold Rooms',
    subtitulo: 'DS 594 · MINSAL food safety',
    desc: 'Mechanical ventilation for receiving areas, fruit/vegetable ripening chambers, back-of-house cold rooms, and bakery areas. Design follows DS 594 and MINSAL food establishment regulations. Cold room panels and door seals specified to minimize temperature variation and energy loss.',
  },
  {
    titulo: 'Shopping Centers & Malls',
    subtitulo: 'Central AHU · Per-tenant metering',
    desc: 'For shopping centers, strip centers, and power centers, we design centralized AHU systems with duct distribution or high-capacity VRF by zone. Independent tenant metering allows energy costs to be billed per store. We have experience with the technical specifications of major Chilean mall operators (Parque Arauco, Mall Plaza, Grupo Patio).',
  },
  {
    titulo: 'Multi-Store Maintenance Contracts',
    subtitulo: 'Fleet contracts · National SLA',
    desc: 'For chains with multiple locations, we offer centrally coordinated preventive maintenance contracts: scheduled visits program, centralized equipment registry, consolidated monthly reports, and 24/7 emergency response under SLA. We cover all of Chile under a single contract — one point of contact for your entire HVAC and refrigeration fleet.',
  },
]

const FAQ = [
  {
    question: 'How much energy does supermarket refrigeration use in Chile?',
    answer: "A mid-size supermarket (1,500–4,000 m² sales floor, 30–60 linear meters of display cases) consumes 180–400 kWh/m²/year in refrigeration. This represents 40–60% of the store's total electricity bill. Migrating to CO₂ transcritical systems (R-744) or upgrading to electronic expansion valve controllers can reduce consumption by 20–35%.",
  },
  {
    question: 'Which refrigerants are used in Chilean supermarkets today?',
    answer: 'Systems installed before 2018 mostly use R-404A (GWP 3,922), which is being phased out. New projects in Chile use R-448A or R-449A (lower-GWP drop-ins) or CO₂ transcritical (R-744, GWP=1) for larger installations. CO₂ transcritical is gaining ground in Chilean supermarkets for its energy efficiency in temperate climates (Santiago, central region) and the elimination of regulatory risk from high-GWP refrigerants under the Kigali Amendment.',
  },
  {
    question: 'What regulations apply to retail refrigeration in Chile?',
    answer: 'Supermarkets and food retailers are subject to DS 977 (MINSAL Food Safety Regulations), which sets maximum storage temperatures by food type. DS 594 regulates working conditions in cold rooms (temperature, PPE, emergency systems). New projects or renovations involving changes to refrigerant piping require SEC (Superintendencia de Electricidad y Combustibles) approval of installation drawings. We manage the SEC process as part of the project.',
  },
  {
    question: 'Can you respond to refrigeration emergencies on weekends and holidays?',
    answer: 'Yes. For clients with Priority maintenance contracts, we provide 24/7 emergency response including weekends and public holidays. A refrigeration failure in an active supermarket can mean CLP 5–30 million in lost merchandise within hours — response time is critical. We stock high-rotation spare parts (compressors, valves, controllers) for the most common brands to reduce repair time.',
  },
  {
    question: 'Can you install HVAC for stores in Chilean shopping malls?',
    answer: "Yes. For stores in shopping centers (fashion, food service, services), we install VRF or high-wall split systems sized to the space and mall specifications. Installation must comply with the mall's technical requirements (installation standards, permitted refrigerant types, condensers in designated technical floors). We have worked in major Chilean malls operated by Parque Arauco, Mall Plaza, and Grupo Patio and understand their specific technical requirements.",
  },
  {
    question: 'Do you handle both HVAC and commercial refrigeration, or just one?',
    answer: "Both — and this is our main differentiator in retail. Most Chilean HVAC contractors do HVAC only; refrigeration contractors do refrigeration only. D&Z Building covers both under a single contract, with one technical team, one point of contact, and one SLA. This is especially valuable for multi-store chains: one provider manages your entire HVAC + refrigeration fleet, coordinates preventive maintenance visits, and responds to emergencies across all your locations.",
  },
]

const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: `${siteUrl}/en/` },
        { '@type': 'ListItem', position: 2, name: 'Sectors', item: `${siteUrl}/en/sectors/` },
        { '@type': 'ListItem', position: 3, name: 'Retail', item: `${siteUrl}/en/sectors/retail/` },
      ],
    },
    {
      '@type': 'Service',
      '@id': `${siteUrl}/en/sectors/retail/#service`,
      name: 'Retail HVAC & Commercial Refrigeration in Chile',
      description:
        'HVAC design, supply, and installation for retail in Chile: supermarket sales floors, display case systems, CO₂ transcritical compressor racks, and multi-store SLA maintenance contracts.',
      provider: {
        '@type': 'LocalBusiness',
        '@id': `${siteUrl}/#business`,
        name: 'D&Z Building SpA',
      },
      areaServed: { '@type': 'Country', name: 'Chile' },
      serviceType: 'Retail HVAC and Refrigeration',
      url: `${siteUrl}/en/sectors/retail/`,
    },
    {
      '@type': 'FAQPage',
      '@id': `${siteUrl}/en/sectors/retail/#faq`,
      mainEntity: FAQ.map(f => ({
        '@type': 'Question',
        name: f.question,
        acceptedAnswer: { '@type': 'Answer', text: f.answer },
      })),
    },
  ],
}

export default function EnSectorRetailPage() {
  return (
    <>
      <Script id="ld-retail-en" type="application/ld+json">
        {JSON.stringify(jsonLd)}
      </Script>

      <div className="sp-wrap">
        {/* Nav */}
        <nav className="sp-topnav">
          <Link href="/en/" style={{ display: 'flex', alignItems: 'center' }}>
            <Image src="/logo.png" alt="D&Z Building" width={110} height={36} style={{ objectFit: 'contain' }} priority />
          </Link>
          <div style={{ display: 'flex', gap: 16, alignItems: 'center' }}>
            <Link href="/en/services/" style={{ color: 'var(--dim)', fontFamily: "'Josefin Sans',sans-serif", fontSize: '11px', letterSpacing: '.1em', textTransform: 'uppercase', textDecoration: 'none' }}>
              Services
            </Link>
            <Link href="/en/#contacto" className="sp-hero-cta" style={{ fontSize: '11px' }}>
              Request a quote
            </Link>
          </div>
        </nav>

        {/* Hero */}
        <div className="sp-hero">
          <div className="sp-breadcrumb">
            <Link href="/en/" style={{ color: 'inherit', textDecoration: 'none' }}>Home</Link>
            <span>›</span>
            <Link href="/en/sectors/" style={{ color: 'inherit', textDecoration: 'none' }}>Sectors</Link>
            <span>›</span>
            <span>Retail</span>
          </div>
          <p style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: '10px', letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--accent)', margin: '0 0 14px' }}>
            Supermarkets · Malls · Chain Stores
          </p>
          <h1 className="sp-hero-title">Retail HVAC &amp; Refrigeration<br />in Chile</h1>
          <p style={{ color: 'var(--dim)', fontFamily: "'Outfit',sans-serif", fontSize: 'clamp(15px,1.6vw,18px)', maxWidth: 700, lineHeight: 1.65, margin: '0 0 28px' }}>
            Integrated HVAC and commercial refrigeration under one contract —
            sales floor comfort, display case systems, CO₂ transcritical racks,
            and multi-store SLA maintenance across Chile.
          </p>
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
            <Link href="/en/#contacto" className="sp-hero-cta">Request a Quote</Link>
            <Link href="/en/services/" className="sp-hero-cta sp-hero-cta-outline">All Services</Link>
          </div>
        </div>

        {/* Stats strip */}
        <div style={{ borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)', padding: 'clamp(18px,2vw,24px) clamp(20px,6vw,96px)', display: 'flex', gap: 32, flexWrap: 'wrap', background: 'var(--bg2)' }}>
          {[
            { val: '180–400', unit: 'kWh/m²/year', label: 'Supermarket energy benchmark' },
            { val: '−30%', unit: 'CO₂ R-744', label: 'vs R-404A systems' },
            { val: '24/7', unit: 'SLA', label: 'Emergency response for fleet clients' },
            { val: 'HVAC+Refrig', unit: '', label: 'Both under one contract' },
          ].map((s, i) => (
            <div key={i}>
              <div style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: 'clamp(18px,2.2vw,28px)', color: 'var(--accent)', letterSpacing: '-.01em', lineHeight: 1 }}>
                {s.val}{s.unit && <span style={{ fontSize: '14px', marginLeft: 2, opacity: 0.8 }}>{s.unit}</span>}
              </div>
              <div style={{ fontFamily: "'Outfit',sans-serif", fontSize: '13px', color: 'var(--text)', marginTop: 4 }}>{s.label}</div>
            </div>
          ))}
        </div>

        {/* Solutions */}
        <div className="sp-section">
          <p style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: '10px', letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--accent)', margin: '0 0 10px' }}>
            Solutions
          </p>
          <h2 style={{ fontFamily: "'Josefin Sans',sans-serif", fontWeight: 300, fontSize: 'clamp(20px,2.5vw,30px)', margin: '0 0 32px', color: 'var(--text)' }}>
            What We Install in Retail Projects
          </h2>
          <div className="sp-aplic-grid">
            {SOLUTIONS.map((s, i) => (
              <div key={i} className="sp-aplic-item">
                <div>
                  <h3 style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: '13px', fontWeight: 400, letterSpacing: '.04em', textTransform: 'uppercase', color: 'var(--text)', margin: '0 0 4px' }}>
                    {s.titulo}
                  </h3>
                  <span style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--accent)' }}>
                    {s.subtitulo}
                  </span>
                </div>
                <p style={{ fontFamily: "'Outfit',sans-serif", fontSize: '14px', color: 'var(--dim)', lineHeight: 1.6, margin: 0 }}>
                  {s.desc}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* FAQ */}
        <div className="sp-section">
          <p style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: '10px', letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--accent)', margin: '0 0 10px' }}>
            FAQ
          </p>
          <h2 style={{ fontFamily: "'Josefin Sans',sans-serif", fontWeight: 300, fontSize: 'clamp(20px,2.5vw,30px)', margin: '0 0 32px', color: 'var(--text)' }}>
            Refrigerants, regulations and costs
          </h2>
          <div style={{ maxWidth: 820 }}>
            {FAQ.map((f, i) => (
              <div key={i} style={{ borderTop: '1px solid var(--border)', padding: '20px 0' }}>
                <h3 style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: 'clamp(13px,1.3vw,15px)', fontWeight: 400, letterSpacing: '.02em', color: 'var(--text)', margin: '0 0 10px' }}>
                  {f.question}
                </h3>
                <p style={{ fontFamily: "'Outfit',sans-serif", fontSize: '15px', color: 'var(--dim)', lineHeight: 1.7, margin: 0 }}>
                  {f.answer}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Related */}
        <div className="sp-section" style={{ paddingTop: 0 }}>
          <p style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: '10px', letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--dim)', margin: '0 0 16px' }}>
            Related services
          </p>
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
            <Link href="/en/services/commercial-refrigeration/" style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: '11px', letterSpacing: '.08em', textTransform: 'uppercase', color: 'var(--accent)', textDecoration: 'none', border: '1px solid var(--border)', padding: '10px 18px' }}>
              Commercial Refrigeration →
            </Link>
            <Link href="/en/services/vrf-systems/" style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: '11px', letterSpacing: '.08em', textTransform: 'uppercase', color: 'var(--dim)', textDecoration: 'none', border: '1px solid var(--border)', padding: '10px 18px' }}>
              VRF Systems →
            </Link>
            <Link href="/en/services/preventive-maintenance/" style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: '11px', letterSpacing: '.08em', textTransform: 'uppercase', color: 'var(--dim)', textDecoration: 'none', border: '1px solid var(--border)', padding: '10px 18px' }}>
              Preventive Maintenance →
            </Link>
            <Link href="/en/sectors/" style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: '11px', letterSpacing: '.08em', textTransform: 'uppercase', color: 'var(--dim)', textDecoration: 'none', border: '1px solid var(--border)', padding: '10px 18px' }}>
              All sectors →
            </Link>
          </div>
        </div>

        {/* CTA */}
        <div className="sp-cta-bar">
          <p style={{ fontFamily: "'Josefin Sans',sans-serif", fontSize: '10px', letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--accent)', margin: '0 0 14px' }}>
            Planning a retail HVAC project in Chile?
          </p>
          <h2 style={{ fontFamily: "'Josefin Sans',sans-serif", fontWeight: 300, fontSize: 'clamp(22px,2.8vw,36px)', margin: '0 0 14px', color: 'var(--text)' }}>
            One contract for HVAC and refrigeration — we handle both
          </h2>
          <p style={{ color: 'var(--dim)', fontFamily: "'Outfit',sans-serif", margin: '0 0 28px', fontSize: 'clamp(14px,1.4vw,17px)', maxWidth: 520, marginLeft: 'auto', marginRight: 'auto' }}>
            New stores or chain renovations: technical quote.
            Multi-store maintenance contracts: proposal within 72 hours with a scheduled visits program.
          </p>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link href="/en/#contacto" className="sp-hero-cta">Get in Touch</Link>
            <Link href="/en/services/" className="sp-hero-cta sp-hero-cta-outline">View all services</Link>
          </div>
        </div>

        {/* Footer */}
        <footer className="sp-footer">
          <Link href="/en/" style={{ display: 'flex', alignItems: 'center' }}>
            <Image src="/logo.png" alt="D&Z Building" width={90} height={30} style={{ objectFit: 'contain' }} />
          </Link>
          <span style={{ color: 'var(--dim)', fontFamily: "'Josefin Sans',sans-serif", fontSize: '11px', letterSpacing: '.06em' }}>
            © {new Date().getFullYear()} D&amp;Z Building SpA
          </span>
        </footer>
      </div>
    </>
  )
}
